# This package only defines the toolchain type for lightningcss-cli.
# The toolchains are generated automatically via module extension.

package(default_visibility = ["//visibility:public"])

toolchain_type(name = "toolchain_type")
